### ISSUE TITLE
Feature Request: Block by Perceptual Hash

### ISSUE THREAD

**Issue by David-Wells99** [GramThanos/NSFW-Image-Filter-Browser-Extension#2]
For my use case, I would like to block male/male gay images, as some people raid straight porn forums with them. As much as AI has advanced, I think that the ad block model of crowd sourcing the work to humans and compiling shared block lists is still valuable.

I ask you consider implementing this model as an alternative. All computation can probably be done client side, as calculating and comparing a perceptual hash is much less intensive than using machine learning.

Thank you for the consideration.

**Comment by GramThanos** [comment]
This project uses the model from https://github.com/gantman/nsfw_model 
That model was trained to categorize the images into the categories drawings, hentai, neutral, porn and sexy.

This project's aim is not to create/maintain models. You may ask for such an option on the nsfw model's projects.
