### ISSUE TITLE
 Missing 'manifest_version' key. 

### ISSUE THREAD

**Issue by asfarmed** [GramThanos/NSFW-Image-Filter-Browser-Extension#6]
Missing 'manifest_version' key. Its value must be an integer either 2 or 3. See developer.chrome.com/extensions/manifestVersion for details.
Could not load manifest.

![image](https://user-images.githubusercontent.com/6324103/161407890-68a80ebc-bca5-4aef-8e0d-3eb62e3b02ff.png)

**Comment by GramThanos** [comment]
You are loading the wrong folder. Select the `dist` folder not the repository's root.
